FROM pytorch/pytorch:2.9.1-cuda13.0-cudnn9-runtime

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
      ffmpeg git curl && rm -rf /var/lib/apt/lists/*

ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} dlcuser && useradd -m -u ${UID} -g ${GID} dlcuser

COPY deeplabcut-webapp-docker-supports/dlc-3D/requirements-lp.txt /tmp/req-lp.txt
RUN pip install --no-cache-dir -r /tmp/req-lp.txt

WORKDIR /app
COPY --chown=dlcuser:dlcuser deeplabcut-webapp-docker-supports/dlc-3D/src/ /app/

USER dlcuser
CMD ["celery", "-A", "dlc_3d_bp.lp.celery_app", "worker", \
     "--loglevel=info", "--concurrency=1", "--pool=prefork", "-Q", "lp_3d"]
